### ISSUE TITLE
Use .rprofile to populate various templates

### ISSUE THREAD

**Issue by CrumpLab** [CrumpLab/vertical#11]
A vertical project will set up various templates, such as a papaja template for an APA manuscript, or other template for slide deck or poster.

It would be neat to be able to automatically assign some basic user data to the yml fields in the loaded templates, such as author name, perhaps pulling from an rprofile or something similar. For now, it'll be up to the user to modify each template accordingly.

**Comment by mvuorre** [comment]
There's quite a bit of stuff that would benefit if users had some info in their .rprofile. So there could be a link to how to do that (I think in devtools documentation), instead of duplicating here. But I think that information should be used by e.g. papaja, so instead of writing code to use it in vertical, I suggest a better solution is to draft how e.g. papaja could use it and send a PR.

**Comment by CrumpLab** [comment]
Completely agree on the strategy to suggest changes to packages that vertical imports, rather than handling auto-population in vertical. I'm going to close this issue for now, and also note that I added a pointer to the usethis documentation for generating DESCRIPTION files in the getting started tutorial.
