### ISSUE TITLE
Hardcode fewer things

### ISSUE THREAD

**Issue by mvuorre** [CrumpLab/vertical#47]
A major weakness of vertical right now is hardcoding of directories and files. This is most obvious in `build_vertical()` and _pkgdown.yml. We should consider alternatives for source discovery and rendering.

One method could be to discover all `<path>/<file>.Rmd` files, then render them to `docs/<path>/<file>.Rmd`, and then check if that path exists in _pkgdown.yml. If not, either write it in there with appropriate prose, or print a warning to the user that "path/file exists, but is not linked to in the navbar".

If you look at the current source of `build_vertical()`, that's basically what it is doing except that it's looking for very specific files/locations. Could easily be replaced with 

```
items <- list.files(..., pattern = ".Rmd", recursive = TRUE)
for i in items rmarkdown::render(...)
```

Then the only exceptions would be to exclude the vignettes folder from the above search (handled by pkgdown), and experiments.

**Comment by CrumpLab** [comment]
I agree, these kinds of improvements would be good. 

Here's a straightforward scheme: Render all .rmds in all folders and subfolders (exclusive of R package and pkgdown folders).

Then, set up the yml to include folder names as tabs in the navbar, subfolder names as sections in the drop down, and titles as titles in the dropdown.

**Comment by mvuorre** [comment]
Started in 90465b9

Sounds good. I am not sure if we want to do any edits to the yml file though. Presumably people will want to customize the navbar and looks quite a bit, so having vertical functions never touch that file seems reasonable (also reduces complexity for both user and developer, as users will need to manually edit it anyway.)

**Comment by CrumpLab** [comment]
Nice, this looks good.

It seems we are circling around yml issues. On the one hand, I can appreciate the simplicity of never having vertical touch `_pkgdown.yml`. This forces users to become more familiar with pkgdown, and learn what that file is actually doing. A plus, and easier for maintenance. On the other hand, having some functionality to automate yml in vertical is also a plus. 

I wonder about this proposal...

1. Take `update_yml()` out of `build_vertical()`
2. create a new `suggest_yml()` function. The goal of this function would be to print example yml to the console that could then be copied by the user to `_pkgdown.yml`

This has the feature of not directly writing the yml, but also providing a convenience function for generating yml. In terms of maintenance, the suggestion function could likely be improved over time, but vertical would not depend on it in any meaningful way.

What do you think?

**Comment by CrumpLab** [comment]
made a few small improvements in 7f8adfbfd0583420e1d1bba1f465793755f86f4f 


- don't build vignettes
- usethis::ui_info rather than warnings for _pkgdown.yml
- report output file names for warnings, not .rmd

**Comment by CrumpLab** [comment]
A few more improvements in 9659030ae8deb11466108ff99a0b4c70f84a09a3

- deleted update_yml()
- removed update_yml() from build_vertical()
- added suggest_yml() as a standalone function to suggest yml for _pkgdown.yml

`suggest_yml()` copies a suggested yml to the console. It works pretty well (no hard-coding for searching folders, just some hard-coding for excluding folders), but there are two issues:

1. It doesn't know the output file type, so assumes .html and writes all hrefs as .html. This causes a dead link for manuscript.pdf, or other .pdfs, need to improve this

2. Not specifically an issue with `suggest_yml()`, but the vignette articles template includes a line to call `library(packagename)`. If the R package is not compiled there will be a build failure because the library does not exist.

**Comment by CrumpLab** [comment]
My sense if that we addressed most of the hard coding issues...what do you think about closing this issue?

**Comment by mvuorre** [comment]
Looks good!
