### ISSUE TITLE
jspsych

### ISSUE THREAD

**Issue by yangepi** [CrumpLab/vertical#61]
Hi, thanks for the package.
When I try to create a vertical project, I had this error:

trying URL 'https://github.com/jspsych/jsPsych/releases/download/v6.2.0/jspsych-6.2.0.zip'
Error in utils::download.file(url = loc_from, loc_to) : 
  cannot open URL 'https://github.com/jspsych/jsPsych/releases/download/v6.2.0/jspsych-6.2.0.zip'
In addition: Warning message:
In utils::download.file(url = loc_from, loc_to) :
  InternetOpenUrl failed: 'An error occurred in the secure channel support'

Not sure why it happens and how to fix it. Thank you

**Comment by CrumpLab** [comment]
Thanks for reporting this. I'm not sure what the issue is, as I can't reproduce it on my side. 

As a workaround, if you intend to have an experiment folder with the jspsych library, then you could create the folder manually, and download the jspsych library yourself and place it in there. Or, if you don't want this, then I would uncheck the jspsych option when creating a vertical project (in which case it shouldn't attempt to download the jspsych library).
