### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by BradyAJohnston** [CrumpLab/vertical#62]
I have just read the paper and am very interested in this approach to experimental analysis and reporting. I'm in biochemistry not psychology, but the same approach I believe is required in all aspects of science. The github repo has been updated since 2020 though so I am just wondering if this project is still a priority before I consider trying to use it in 'production'?

**Comment by CrumpLab** [comment]
Thanks for your interest. We haven’t updated vertical recently mainly because the package is very lightweight, and most of the functionality is carried out by other packages.

One intention of {vertical} was to provide an example to psych researchers about how they could use assorted R packages and conventions to organize and share their research. I totally agree that the general approach could be useful elsewhere.

{Vertical} itself has minimal functionality that can be duplicated without using the package. It installs a vertical project template in R studio that basically loads a R package template with a few extra named folders for research assets that are not normally part of an R package or pkgdown website. So the basic vertical template can be made by creating a new R package project template, and adding any folders you want manually. 

There is also a `build_vertical()` function that is intended as an example make file that can be run to compile multiple files (in non-standard pkgdown folders) and save them into a docs folder (assuming the website will be displayed on github pages). However, the same basic functionality can be accomplished with `pkgdown::build_site()`, copying any additional assets to the docs folder manually, and modifying the _pkgdown.yml` file to add the asset to the tabs in the top-level navigation. 

I would say our plans for further development are medium to low priority.

**Comment by BradyAJohnston** [comment]
Thanks for the information and the work you have done on creating the package. I will be considering implementing either this package or a similar approach that you have detailed moving forward :)
