### ISSUE TITLE
new folders

### ISSUE THREAD

**Issue by CrumpLab** [CrumpLab/vertical#8]
Consider some functionality for adding new folders. E.g., let's say you have a model and want to share scripts for that. You could manually add a `model` folder, put .Rmds in there, compile them, and then manually add them to docs. 

Or, there could be a usethis style function e.g., `vertical_add_folder(folder_name)`, which could add the folder, and potentially automate other things like writing the necessary yml to add compiled Rmds to the website.

**Comment by mvuorre** [comment]
I like this idea. This talks further to the modular design; e.g. all of `vertical`'s functionality could be wrapped in functions and a custom build script, instead of a hard coded template. Those functions could be implemented as rstudio addins, with one master to run them all at init time. This particular one could simply use / instruct users to use `usethis::use_directory(..., ignore = TRUE)`.

**Comment by CrumpLab** [comment]
I've update the getting started tutorial to make suggestions about additional folders. The suggestion is to add them as subfolders in vignettes. The result is that all documents in vignettes, and vignette subfolders is added to the Supplementary tab, and the sub folder names are used as section headers in the drop-down tab. Closing this issue.
